### PR TITLE
fix: repair post-merge storage and Runtime Host contracts

### LINKED ISSUE #3788: fix(storage): converge duplicate session metadata migration 30
## Problem

Current `main` at `689a4515f15870d3c0ae9ee66c2f2021b34c0e2b` has two entries for session metadata migration version `30` in `packages/storage/src/sqlite-session-metadata-schema.ts`:

- #3721 / merge `24a97c54e`: creates `message_admissions` and `cancelled_message_admissions`;
- #3764 / merge `f9d960d8c`: creates `session_metadata_one_workhub_coordination_session`.

`MIGRATIONS` is constructed as a JavaScript `Map`, so the later `[30, ...]` silently replaces the earlier one. A fresh database advances `session_metadata_schema` to version 30 after creating only the coordination index. The message-admission store then fails with `no such table: message_admissions`.

## Reproduction

On current main after building `@maka/core` and `@maka/storage`:

```text
node@24 --test --test-concurrency=1 \
  --test-name-pattern="materializes an accepted steering draft" \
  packages/storage/dist/__tests__/sqlite-session-metadata-store.test.js
```

Result:

```text
Error: no such table: message_admissions
```

The complete session metadata file reports five failures in the admission/handoff/reorder tests. I reproduced the same failure after stashing an unrelated Windows-baseline branch and rebuilding pure `upstream/main`, so it is not introduced by that branch.

## Merge interaction

Both PR heads could be green independently because each owned version 30 on its own base. The conflict is semantic rather than textual and appeared only after both merges.

## Required compatibility

Simply renumbering the latest source entry is insufficient because version-30 databases may already exist in three shapes:

1. #3721 head: message-admission tables exist, coordination index absent;
2. #3764 head: coordination index exists, message-admission tables absent;
3. current main: same as (2), with schema version recorded as 30.

Recommend bumping the current schema to 31 and making migration 31 converge every version-30 shape with guarded creation of both authorities. Add tests for all three starting shapes and a contract that prevents duplicate migration-version declarations from being silently collapsed by `Map` construction.

This is a current-main storage migration blocker, independent of #2624.

### LINKED ISSUE #3790: fix(runtime-host): migrate queue tests off removed connection aliases
## Problem

Current `main` at `689a4515f15870d3c0ae9ee66c2f2021b34c0e2b` does not build after #3784 removed operation-specific `RuntimeHostConnection` aliases.

`packages/runtime-host/src/__tests__/execution-host-queue.test.ts` still calls the removed methods:

```text
TS2339: Property 'queryTurn' does not exist on type 'RuntimeHostConnection'.
TS2339: Property 'stopTurn' does not exist on type 'RuntimeHostConnection'.
TS2339: Property 'startTurn' does not exist on type 'RuntimeHostConnection'.
```

## Evidence

- Main CI is red: https://github.com/apache/maka/actions/runs/32842310303
- #3789's newly automatic Windows recovery check fails at `Build test artifacts` before any recovery test runs: https://github.com/apache/maka/actions/runs/32844342483/job/97790574974
- #3784's PR check was green on its pre-merge head, but its merge commit includes current-main test changes that still use the aliases.

## Expected fix

Migrate the stale test calls to the typed request API (`turn.query`, `turn.stop`, and `turn.start`) while preserving the exact assertions and test semantics. Run the complete Runtime Host build/test plus current-main CI.

This is a current-main regression independent of #3789/#2624.

### PR DESCRIPTION
**Pull request by liugddx**
## Summary

Repair two independent post-merge regressions that currently form a required-CI bootstrap loop on `main`:

1. #3721 and #3764 both assigned session metadata migration version 30. JavaScript `Map` construction silently retained only the later migration, so current-main databases record version 30 without creating `message_admissions`.
2. #3784 removed operation-specific `RuntimeHostConnection` aliases but left three queue-test calls on `queryTurn`, `stopTurn`, and `startTurn`, so current main does not build.

The fixes remain separate commits in this PR.

## Migration compatibility

Schema version advances to 31. Migration 30 retains the admission-table authority introduced by #3721. Migration 31 uses guarded creation to converge every version-30 shape that may already exist:

- admission tables only (#3721 head);
- WorkHub coordination index only (#3764 head and current main);
- both objects present.

Fresh/older databases run 30 then 31 and reach the same schema. Module initialization now verifies that migration keys cover every version exactly once by rejecting duplicate-or-missing `Map` entries.

The session metadata constructor also closes a newly opened `DatabaseSync` when schema configuration or migration rejects, so a newer-schema refusal does not leak its handle on Windows.

## Runtime Host test migration

The three stale calls are migrated to the existing typed operations without changing inputs or assertions:

- `turn.query`
- `turn.stop`
- `turn.start`

## Verification

- Session metadata store: 56 passed, 0 failed, including all three version-30 starting shapes and the five message-admission tests previously failing on main.
- Core, Storage, MCP, Runtime, and Runtime Host builds: passed.
- Runtime Host queue suite starts and exercises the repaired storage authority; 9/12 passed locally. Three tests hit the existing fixed 10-second Host-readiness deadline on this Windows machine, with no process error or protocol failure. The directly changed production UDS test passed in the first complete run; hosted CI is authoritative for timing.
- lint, format, and `git diff --check`: passed.

Fixes #3788. Fixes #3790.

## AI use

Codex diagnosed the semantic merge collision, implemented the compatibility migration and stale-call updates, and ran the listed checks.
## Checklist

- [x] Tests cover the change and fail without it
- [x] Core/Storage/MCP/Runtime/Runtime Host builds pass locally
- [x] Session metadata migration and message-admission suites pass locally
- [x] Lint, format, and `git diff --check` pass
- [x] Exact-head required `test` passed before the trailer-only history rewrite; a fresh check was triggered for the new head

Does this PR entail a change in behavior?

- [x] Yes - existing version-30 databases converge to schema 31 without losing either merged authority; stale test callers use the supported typed request API.
- [ ] No

### CODE REVIEW

**Review by M4n5ter — APPROVED** [review]
Reviewed the typed-request migration and the version-30 schema convergence. The changes preserve the affected test semantics, cover every known merged version-30 shape, and keep initialization failure cleanup bounded. Current CI is green and later main commits do not overlap these files.
