### ISSUE TITLE
bug(storage): main build fails on undefined decodeStoredMessage in Codex adapter test

### ISSUE THREAD

**Issue by liugddx** [apache/maka#3655]
## What happened

The current `main` branch does not compile. `packages/storage/src/__tests__/codex-session-adapter.test.ts` calls `decodeStoredMessage(message)`, but that identifier is neither declared nor imported.

The failure blocks the repository build and every PR synchronized with current main:

```text
src/__tests__/codex-session-adapter.test.ts(267,26): error TS2304: Cannot find name 'decodeStoredMessage'.
```

Expected: the Codex adapter regression test compiles and validates every emitted message through the canonical message decoder already imported by the file.

## How to reproduce

1. Checkout current main at `c79e9eb40ee4a0fcd204fb075427d635989eaaca`.
2. Run `npm ci`.
3. Run `npm --workspace @maka/storage run build`.
4. Observe TypeScript fail at line 267 before tests execute.

The same failure is visible in main CI run 32664680331 and in PR #3617 after synchronizing main.

## Environment

- Maka commit: `c79e9eb40ee4a0fcd204fb075427d635989eaaca`
- OS: macOS 13 arm64 locally; Ubuntu 24.04 in hosted CI
- Surface: storage build/test
- Node.js: v23.11.0 locally; CI uses the repository Node setup

## Logs, screenshots, or additional context

The test file already imports `decodeCanonicalMessage` from `@maka/core/session`, and the preceding Codex adapter test uses it to validate adapter output. The equivalent Claude adapter test also validates imported adapter messages with `decodeCanonicalMessage`.

This appears to be a one-line test typo introduced with #3520: replace `decodeStoredMessage(message)` with `decodeCanonicalMessage(message)`. No production path needs to change.
