### PR TITLE
fix(cli): declare the transcript viewer's mid-turn disposition

### PR DESCRIPTION
**Pull request by Astro-Han**
## Summary

`main` does not typecheck. `MakaSlashCommand.midTurn` became required so every handler has to state whether it is safe to run while a turn is in flight; `/transcript` (#2999) landed in parallel and never got an answer:

```
packages/cli/src/pi-tui-runner.ts(2877,5): error TS2741: Property 'midTurn' is missing in type
'{ description: string; run: (parts: string[]) => void; }' but required in type
'Omit<MakaSlashCommand, "aliases" | "name">'.
```

Neither PR was wrong on its own — the conflict is semantic, so both merged green and `main` broke. The viewer is a full-screen overlay over the same TUI the running turn paints into, which is the picker case `'refuse'` exists for, so that is its declared answer.

Refs #2999

## Verification

- `npm run build` — passes with this change, fails on `main` without it
- `npm run format:check` — clean
- `npm test --workspace maka-agent` — 371 pass, 0 fail

## AI use

Select exactly one:

- [ ] No generative tool made a substantive contribution
- [x] Generative tooling made a substantive contribution

Tool(s) and scope: Claude Code diagnosed the cross-PR type break and wrote the one-line declaration and its comment. The human contributor reviewed the diff and the disposition choice.

## Checklist

- [ ] Tests cover the change and fail without it
- [x] Lint, format, typecheck and the affected suites pass locally

The compiler is the test: `main` fails to build without this change.

Does this PR entail a change in behavior?

- [x] Yes — described under Summary above
- [ ] No

`/transcript` is now refused mid-turn instead of opening over a running turn.

### CODE REVIEW

**Comment by Astro-Han** [comment]
Superseded by #3459, which landed the same declaration on `main` in b434a491. `main` builds again, so this is redundant — closing.

One correction worth recording for anyone who hits this next: the value that landed is `midTurn: 'local'`, not `'refuse'`. The type's own doc comment draws the line at whether the handler enters `runControl` — `'local'` requires the handler to be independent of the running turn, `'refuse'` is for anything that mutates session state or opens a picker the turn would race. `showTranscriptViewer` only calls `tui.showOverlay` and never touches `runControl`, so `'refuse'` would have compiled while silently disabling `/transcript` exactly when reading back is most useful.

Review assisted by AI (Claude Opus 5).
